### PR TITLE
finalshell: Add version 3.9.5.7

### LINKED ISSUE #309: [Request] 请求添加一个FinalShell
<!-- **Please describe the app you want to add.**
Final Shell: http://www.hostbuf.com/t/988.html
FinalShell是一体化的的服务器,网络管理软件,不仅是ssh客户端,还是功能强大的开发,运维工具,充分满足开发,运维需求.

### PR DESCRIPTION
**Pull request by b4imetu**
Close #309 
code modified from [ViCrack/scoop-bucket](https://github.com/ViCrack/scoop-bucket/blob/master/bucket/finalshell.json)

### CODE REVIEW

**Comment by b4imetu** [comment]
Upstream issue
The actual downloaded package version is 3.9.5.7, but the official website shows 3.9.5.4, the regEX can only match to 3.9.5.4.
Already sent an email to the author.

**Comment by chawyehsu** [comment]
Copying manifests from repos with licenses is not acceptable for me.

**Comment by ViCrack** [comment]
> Upstream issue The actual downloaded package version is 3.9.5.7, but the official website shows 3.9.5.4, the regEX can only match to 3.9.5.4. Already sent an email to the author.


@b4imetu  I've fixed the problem. 

https://github.com/ViCrack/scoop-bucket/commit/511159d2f0f87749a95766b693b647a59bfd9f1d

> @ViCrack I May need your help with the license issue

 is acceptable for me

**Comment by b4imetu** [comment]
@chawyehsu plz reopen this pr to close #309 , which was tagged `contribution welcome` on May 13, 2021
This is just a common community-maintained manifest. There should be no license issue.
Thank you very much

**Pull request closed without merging**
