### PR TITLE
microsoftedge: Add version 83.0.478.61

### PR DESCRIPTION
**Pull request by chawyehsu**
**WIP**

failed in PowerShell 6+, due to https://github.com/PowerShell/PowerShell/issues/2896
```
$ curl -X GET -I https://api.shuax.com/v2/download/edge/stable/x86
HTTP/1.1 307 Temporary Redirect
Server: nginx
Date: Sun, 02 Feb 2020 12:12:50 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Location: http://msedge.f.tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/6aadba07-0e75-4d32-9302-217f397442dd?P1=1580731970&P2=402&P3=2&P4=ZLh8MNIdMlAi0b4VoMsUeNr%2bqgB4AXlHbT3%2bzJ%2fkuDNFQi2B%2bJidmzST80ufikrwf0ohJWoLkY0eL86zUaAu4w%3d%3d
Vary: Accept-Encoding
```

Solution: ~~change download API endpoint, or wait for PowerShell updates.~~ https://github.com/lukesampson/scoop/pull/3902

credit: the download endpoint is provided by https://tools.shuax.com/edge/ created by @shuax

### CODE REVIEW

**Comment by kidonng** [comment]
Hi, I created a proxy for this: `https://edge-dl.kidonng.workers.dev/`, just prepend it to the URL.

Also there is an issue with the manifest, there will still be a directory named with the version after extracting, so Scoop will fail to create the shortcut.

You can checkout my version of the manifest here: https://github.com/kidonng/sushi/blob/master/bucket/microsoft-edge.json (by the way, `https://scoop-services.azurewebsites.net/` is being used for `checkver`, is it operated by you? if you think it is unsuitable for me to use the service I will create mine.)

**Comment by chawyehsu** [comment]
@kidonng the proxy works well, nice. I'll use it until https://github.com/lukesampson/scoop/pull/3902 being merged into scoop's master branch.

> `https://scoop-services.azurewebsites.net/` is being used for `checkver`, is it operated by you? 

Yep, it's created and operated by me to replace `https://h404bi.azurewebsites.net/`. It's ok to use anytime and anywhere if it's helpful for you.

**Comment by chawyehsu** [comment]
Besides, downloading from the proxy is slow.

**Comment by kidonng** [comment]
😅 That depends on your connection speed to Cloudflare, which can be slow if one doesn't use a proxy.

**Pull request merged**
