### PR TITLE
Add qbittorrent-enhanced-portable v4.3.3.10

### PR DESCRIPTION
**Pull request by AkariiinMKII**
resolve https://github.com/chawyehsu/dorado/issues/255
resolve https://github.com/chawyehsu/dorado/pull/257#issuecomment-790464168 and https://github.com/chawyehsu/dorado/pull/257#issuecomment-787492975

### CODE REVIEW

**Comment by escape0707** [comment]
I still don't think that automatically import configs from `LocalAppData` and `AppData` upon each update is a reasonable choice, as users might installed a non-portable or older version of qB or qBEE for PT, etc.
Just a note of how to manually run a one liner to import these folders is good enough.

**Comment by AkariiinMKII** [comment]
> I still don't think that automatically importing configs from `LocalAppData` and `AppData` upon each update is a reasonable choice, as users might installed a non-portable (perhaps also older) version of qB or qBEE just for PT, etc.
> I think a note about how to manually run a one liner to import these folders is already good enough.

The `qBittorrent` folder in persist directory is set as a trigger for importing scripts, if you want a new instance, just delete the sub-folders and go. I'll add a note for this.
Meanwhile, the shortcut and shim will conflict with ones for non portable version, renaming is needed for multiple running

**Comment by AkariiinMKII** [comment]
> I still don't think that automatically importing configs from `LocalAppData` and `AppData` upon each update is a reasonable choice, as users might installed a non-portable (perhaps also older) version of qB or qBEE just for PT, etc.
> I think a note about how to manually run a one liner to import these folders is already good enough.

我还是说中文吧😂
这个manifest预期的使用情景是替代而不是并行，对于并行实例的需求只需要删除`$persistdir\qBittorrent`下面的子文件夹即可，只要不删除`qBittorrent`文件夹本身就不会触发导入流程
目前计划移除shim并修改shortcut来避免并行冲突

**Comment by escape0707** [comment]
> The qBittorrent folder in persist directory is set as a trigger for importing scripts
哦哦，我没注意到是用的 persist 里的 Orz。当时看成判断 (local)appdata 里有没有文件夹了。。

> renaming is needed for multiple running
这个倒是，我之前确实是自己加了个快捷方式。

另外我想起来 scoop 的软件还是默认便携模式比较好。感觉之前提新开一个 manifest 的想法的时候一定是因为看了 extras/qb 那边就想当然了。我现在装软件之前还要 search 一下有没有便携版，search 又超慢，很不方便。能默认便携还是默认便携比较好？

用新的快捷方式这个很🉑。

**Comment by AkariiinMKII** [comment]
> > The qBittorrent folder in persist directory is set as a trigger for importing scripts
> 哦哦，我没注意到是用的 persist 里的 Orz。当时看成判断 (local)appdata 里有没有文件夹了。。
> 
> > renaming is needed for multiple running
> 这个倒是，我之前确实是自己加了个快捷方式。
> 
> 另外我想起来 scoop 的软件还是默认便携模式比较好。感觉之前提新开一个 manifest 的想法的时候一定是因为看了 extras/qb 那边就想当然了。我现在装软件之前还要 search 一下有没有便携版，search 又超慢，很不方便。能默认便携还是默认便携比较好？
> 
> 用新的快捷方式这个很🉑。
> 

感觉scoop在理念上还是侧重把相关文件留在scoop目录来减少对系统文件目录的“污染”

**Pull request closed without merging**
