### PR TITLE
diskgenius-zh: Add version 5.4.3.1328

### PR DESCRIPTION
**Pull request by pessoalzy**
Chinese edition of DiskGenius which uses different licenses from English edition included in Extras bucket.

### CODE REVIEW

**Comment by AkariiinMKII** [comment]
It is recommend to use `diskgenius-cn` instead to avoid naming conflictions

**Comment by pessoalzy** [comment]
If suffix is necessary I think `diskgenius-zh` would be better. Because customer service of DiskGenius told me that these two editions are differentiated by language rather than region. "cn" is a country/region tag while "zh" is a language tag and Chinese edition supports both Traditional Chinese (zh-Hant) and Simplified Chinese (zh-Hans).

**Comment by chawyehsu** [comment]
`diskgenius-zh` looks good to me. According to their website, the license is `Shareware`, could you please update the license? Moreover, I suggest omitting the bin shim for a GUI application.

**Comment by pessoalzy** [comment]
Done. I changed its name, updated the license and removed the "bin".

**Pull request merged**
